name: Si Xu
tagline: PhD Candidate at UCL
career-objective: I am currently a PhD candidate at Centre for Research & Analysis of Migration (CReAM), UCL, London, UK. My supervisors are ... My PhD study is supported by ... Before joining UCL, I received my Master degree from Duke University and my Bachelor Degree from Central University of Finance and Economics. 
color-theme: red # red or blue
avatar-filename: avatar.png # Change to your avatar's filename
url: academicportfolio.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: si.xu.20@ucl.ac.uk
  github: 
    visibility: false
    handle: arnobk
  linkedin: 
    visibility: true
    handle: si-xu-621802225
  WeChat: 
    visibility: false
    handle: arnobdotme

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: false
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Technical Skills
    visibility: false
  publications: 
    label: Publications
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: false
  certifications: 
    label: Certifications
    visibility: false
  achievements: 
    label: Achievements
    visibility: false

navigation:
- title: About
  url: /
- title: Contact
  url: /contact
- title: CV
  url: /statesboro-blues.pdf

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X
