name: Harvey Mannering
tagline: PhD Candidate at University of Southampton
career-objective: I am currently a PhD candidate in the Vision, Learning and Control (VLC) group at the University of Southampton. My supervisors are Zhiwu Huang and Adam Prugel-Bennett. Before starting my PhD, I received my Master degree from UCL, my Bachelor Degree from University of Southampton, and spent four years in industry as a software developer. 
color-theme: red # red or blue
avatar-filename: avatar.png # Change to your avatar's filename
url: harveymannering.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: hgm1g14@soton.ac.uk
  github: 
    visibility: true
    handle: harveymannering
  linkedin: 
    visibility: true
    handle: harvey-mannering-bba308179
  WeChat: 
    visibility: false
    handle: arnobdotme

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: false
    sort_by: year
  achievements:
    output: false
    sort_by: year

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: false
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Technical Skills
    visibility: false
  publications: 
    label: Publications
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: false
  certifications: 
    label: Certifications
    visibility: false
  achievements: 
    label: Achievements
    visibility: false

navigation:
- title: About
  url: /
- title: Contact
  url: /contact
- title: CV
  url: /Research_Resume.pdf

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X
